apiVersion: v1
kind: Service
metadata:
  name: http-sd-endpoint
spec:
  ports:
  - port: 5000
  selector:
    app: http-sd-endpoint
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-sd-endpoint
  labels:
    app: http-sd-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-sd-endpoint
  template:
    metadata:
      labels:
        app: http-sd-endpoint
    spec:
      containers:
      - name: http-sd-endpoint
        image: asia-southeast1-docker.pkg.dev/[PROJECT]/[REPOS]/[IMAGE]:[TAG]
        ports:
        - containerPort: 5000
        # resources:
        #   request:
        #     cpu: 100m
        #     memory: 128Mi
        #   limits:
        #     cpu: 1000m
        #     memory: 1024Mi
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   timeoutSeconds: 2
        #   failureThreshold: 3
          
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   timeoutSeconds: 2     
        #   failureThreshold: 3  